apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jellyfinweb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.jellyfinweb.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.jellyfinweb.service.name }}
                port:
                  number: {{ .Values.jellyfinweb.service.port }}