apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jellyfinweb.service.name }}
spec:
  selector:
    app: {{ .Values.jellyfinweb.selector }}
  ports:
    - name: jellyfinweb
      protocol: TCP
      port: {{ .Values.jellyfinweb.service.port }}
      targetPort: {{ .Values.jellyfinweb.service.targetPort }}